set -g mouse on
set -g base-index 1

set -g status-position top
set -g status-justify absolute-centre
set -g status-right "%I:%M"
set -g status-style bg=white,fg=black

set -g mode-style bg=white,fg=black
set -g message-style bg=white,fg=black

set -g pane-base-index 1
set -g pane-border-lines heavy
set -g pane-border-style fg=#404040
set -g pane-active-border-style fg=#737373

unbind -a
set -g prefix C-g
bind C-g send-prefix

bind    t      new-window
bind    q      confirm-before -p "kill window #W? (y/n)" kill-pane

bind    d      detach-client
bind    r      source-file ~/.tmux.conf
bind    :      command-prompt

bind    v      split-window -v
bind    V      split-window -h

bind -n M-h    select-pane -L
bind -n M-j    select-pane -D
bind -n M-k    select-pane -U
bind -n M-l    select-pane -R

bind -n M-H    resize-pane -L 1
bind -n M-J    resize-pane -D 1
bind -n M-K    resize-pane -U 1
bind -n M-L    resize-pane -R 1

bind -n C-Tab  select-window -n
bind -n C-BTab select-window -p

bind    1      select-window -t :1
bind    2      select-window -t :2
bind    3      select-window -t :3
bind    4      select-window -t :4
bind    5      select-window -t :5
bind    6      select-window -t :6
bind    7      select-window -t :7
bind    8      select-window -t :8
bind    9      select-window -t :9
bind    0      select-window -t :0
