#!/usr/bin/env bash

xrandr -s 2560x1440 -r 200
[[ -e $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

xset -dpms s off
xsetroot -solid "#891446" -cursor_name left_ptr

alacritty --daemon &

#cwm
fvwm3
