#!/usr/bin/env mksh

xrandr -s 2560x1440 -r 144
[[ -e $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources
xsetroot -solid "#891446"
#-cursor_name left_ptr
#hsetroot -cover $HOME/pix/bg.png
xset -dpms s off

qbittorrent &

#sxhkd &
#ruler &
#bar &

#2bwm
#cwm
fvwm3
