daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:73BF-1002:0E3A-0000:2c:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: edge
      interval_ms: 500
      curve:
        30: 0.25
        50: 0.25
        55: 0.4
        75: 0.65
        80: 0.75
      spindown_delay_ms: 0
      change_threshold: 0
    pmfw_options: {}
    power_cap: 293.0
    performance_level: manual
    max_core_clock: 2400
    max_memory_clock: 1050
    voltage_offset: -50
    power_profile_mode_index: 0
    power_states:
      memory_clock:
      - 0
      - 1
      - 2
      - 3
      core_clock:
      - 0
      - 1
